export const CHALLENGE_ROUNDS = 3;
export const CHALLENGE_PAIRS_PER_ROUND = 5;
export const CHALLENGE_REQUIRED_PAIRS = CHALLENGE_ROUNDS * CHALLENGE_PAIRS_PER_ROUND;
export const CHALLENGE_VERSION = "challenge_v1";
export const CHALLENGE_MAX_LEADERBOARD = 10;
export const CHALLENGE_MISTAKE_COOLDOWN_MS = 2000;
export const CHALLENGE_ROUND_TRANSITION_MS = 1000;
